name: 'Terragrunt CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terragrunt-pipeline:
    uses: uj-cpu-dev/terragrunt-pipeline/.github/workflows/ci-cd.yml@main
    with:
      working_dir: live/dev/s3
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}