name: 'Terragrunt CI/CD'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terragrunt-pipeline:
    uses: uj-cpu-dev/terragrunt-pipeline/.github/workflows/ci-cd.yml@main
    with:
      working_dir: live/dev/s3
    secrets: inherit